import Head from "next/head";
import Home from "./Home";
import HeaderNav from "./components/HeaderNav";
import SideBar from "./components/SideBar";
import "@emotion/react";

export default function Index() {
  return (
    <div css={{
      height: '130vh',
      scrollBehavior: 'smooth',
      overflowX: 'hidden',
    }}>
      <Head>
        <title>Home - Anime Collections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />
      <div css={{ display: 'flex' }}>
        <div css={{ flex: '8' }}>
          <Home />
        </div>

        <div css={{ flex: '2' }}>
          <SideBar />
        </div>

      </div>

    </div>
  );
}
