import Head from "next/head";
import Home from "./Home";
import HeaderNav from "./components/HeaderNav";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Home - Anime Collections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />
      <Home />
    </div>
  );
}
